### ISSUE TITLE
confusing between red and orange

### ISSUE THREAD

**Issue by apurvakalia** [dwalton76/rubiks-cube-tracker#12]
The cube scanning seems to be confusing between red and orange for me. I have tried Pi Camera v1.3 as well as v2.0. I have also tried multiple cubes and played around with many settings (AWB gains, contrast, mode etc), but it still gets confused between red and orange on alternate squares. See the attached file - which is the output from the color-resolver program.

[rubiks-color-resolver.html.zip](https://github.com/dwalton76/rubiks-cube-tracker/files/9884412/rubiks-color-resolver.html.zip)

**Comment by dwalton76** [comment]
Red vs. Orange is always a beast :( I am able to reproduce the problem with the output from the html file you attached (thanks)...let me see what I can do

**Comment by apurvakalia** [comment]
Thanks for responding so quickly. A couple of other things that may be important:
- I am actually implementing this on BuildHat (and not on BrickPi3). So my solution is a combination of your code and the original PrimeCuber code
- However, I am using your scanning code pretty much as is since PrimeCuber scans using the color sensor
- Could the problem be related to the direction of spin in between scanning? I dont think so, but thought I would put it out there
- I tried looking into the init.py file to see if there are any tolerances etc that I could tweak but could not see anything obvious
Very interested to see what you find out. So please do let me know

**Comment by dwalton76** [comment]
![image](https://user-images.githubusercontent.com/468309/198595558-1fdbbf92-2a92-499d-aa7d-00427594beba.png)

question...is square 23 Orange and square 41 Red or is it the other way around?

**Comment by apurvakalia** [comment]
I think that is the problem. The actual cube looks like this:
![IMG-7730](https://user-images.githubusercontent.com/65355231/198623140-22e2e03a-6ed5-4b5c-8ada-83b322a1795a.jpg)
![IMG-7731](https://user-images.githubusercontent.com/65355231/198623207-e5dce209-5f5e-4dfa-98da-92123412b605.jpg)

So by that 23 should be Red, right? The dictionary of returned RGB values shows:
'23': (230, 61, 33) ... '41': (180, 0, 7)

If 41 is orange as per the actual cube pictures, then the RGB values seem good (230 is "more" red than 180).

So am I spinning the cube the wrong way in between scans? Or is it some other problem?

**Comment by dwalton76** [comment]
yeah so 23 is Red and 41 is Orange...so we are getting the centers and corners correct but the orange vs red edges are all reversed.  
![image](https://user-images.githubusercontent.com/468309/198628784-8049ead4-379c-443c-8738-472edc389388.png)


You are not doing anything wrong...I suspect this is a bug:

**Comment by apurvakalia** [comment]
Yes, the edges seem to be getting flipped. The RGB values of the edges look good (e.g. '20': (224, 54, 29) vs '38': (172, 0, 5)). So it does look like a bug.....

**Comment by dwalton76** [comment]
I see what was wrong and pushed a fix, do `sudo python3 -m pip install git+https://github.com/dwalton76/rubiks-color-resolver.git` to install the latest code from the repo with the fix and let me know if it works

**Comment by apurvakalia** [comment]
wow! that was quick. Unfortunately, I wont get to testing this later today, but I will try and match your alacrity and let you know as soon as I test it out :) Do I need to uninstall the current install before pulling in the fix? Also, just out of curiosity, what was the bug?

**Comment by dwalton76** [comment]
In a nutshell we were looking at all of the corner squares and classifying them as one of the six colors and we used that to define a baseline RGB for each of the six colors.  For an odd cube though we can do a little better by only using the square in the dead center of each side for defining a baseline RGB for each of the six colors.  For odd cubes we know that:
- yellow must always be opposite white
- red must always be opposite orange
- green must always be opposite blue

so that makes it much easier to get them classified as one of the size colors correctly.

**Comment by apurvakalia** [comment]
Your fix worked! I can now successfully scan the cube 4 times out of 5. Every once in a while the cube becomes a little skewed while turning and then the scanner complains about not finding the black border, but that is a mechanical issue. I need to adjust my flipper so that the cube does not get skewed. Thanks a lot - I am now moving to the next part. Hopefully I can get this working for BuildHat soon....
