### ISSUE TITLE
Raspberry pi camera

### ISSUE THREAD

**Issue by Steven438** [dwalton76/rubiks-cube-tracker#2]
Hi, i want to ask you if it's s possible to use raspberry pi camera instead a webcam. Sorry for making this an issue and hope you will reply to this. Thanks!

**Comment by dwalton76** [comment]
I haven't tried it but I can't think of any reason for it to not work.  Give it a try and let me know how it goes.

**Comment by Steven438** [comment]
I tried with creating a directory where i captured all sides of a 4x4x4 and write in the terminal "rubiks-cube-tracker.py --directory /home/pi/cubescan". The program analysed the files but very slow and did not give me a solution, just a lot of numbers. The reason that i use raspberry pi camera is the fact that my web camera is very old and doesn't  adapt to the light correctly. Any suggestions?

**Comment by dwalton76** [comment]
Speed, it is probably going to be slow on a raspberry pi :( Analyzing the six images takes some CPU cycles, I'm sure it will be much faster on a laptop or desktop.  How long did it take to run on a pi?

You should see a solution printed when using the `--webcam` option, you have to install the following first though:
- https://github.com/dwalton76/rubiks-color-resolver
- https://github.com/dwalton76/rubiks-cube-NxNxN-solver

**Comment by Steven438** [comment]
Yeah i know i installed all of that, but when I put a webcam and use --webcam 0 it works very fast and well, but my webcam it's very old and doesn't adapt to light correctly. So I read in the ReadMe that I can create a directory where I can put the images of the cube with the name "rubiks-side-B.png", .... . So I made that, capturing all 6 pictures with raspberry pi camera and move the photos in that folder and then write in the LX terminal "rubiks-cube-tracker.py --directory/home/pi/cubescan. The program started analyzing the files but very slow, one image at 20 seconds, and when it finished, give me a lot of numbers for example "[126], [174], [286]...
I know that webcam is accessible via dev/video0, and I want to use the raspberry pi camera instead of webcam but I don't know. The webcam doesn't recognize correctly the colors because of light, and I need to try several times to work...

**Comment by dwalton76** [comment]
Ah I see what you mean. I can tweak it to print the solution in non webcam mode but in the meantime you can cut-n-paste that list of numbers and feed them to the rubiks-color-resolver which will give you the state of the cube in a big string of ULFRBD characters. Then feed that cube state to the solver and it will give you the solution.

**Comment by dwalton76** [comment]
I have a Pi3 I can try this on and see how long it takes. What model pi are you using?

**Comment by Steven438** [comment]
I have the pi3 B+

**Comment by Steven438** [comment]
And I have another problem, I cant find the color resolver or cube tracker file on my pi, just the NxNxN solver and I've searched a lot.

**Comment by dwalton76** [comment]
Start with https://github.com/dwalton76/rubiks-color-resolver if you follow the README there and do `which rubiks-color-resolver.py` does it find it?

For https://github.com/dwalton76/rubiks-cube-NxNxN-solver the README also has install instructions

**Comment by Steven438** [comment]
Yeah i installed both i willy try if it works

**Comment by Steven438** [comment]
I tried with the 4x4x4 cube with the state that I find in Read me and resolved the centers but give me a error like "kociemba .... exit status 1". And for the 5x5x5 cube writes "Cannot allocate memory" but I have 14 GB free

**Comment by Steven438** [comment]
![2018-08-07-105916_1824x984_scrot](https://user-images.githubusercontent.com/40627632/43762603-0c53e14a-9a31-11e8-979a-720be566bb12.png)

here is the screenshot for the 4x4x4 cube in the state that i find in Read me... took 3 minutes to compile it.... A previous version of your solver made that in 10 seconds. I tested also that you told me with color resolver - works great but i needed to do it manually and it takes 30 second per image to analyze

**Comment by Steven438** [comment]
Now i dropped pi camera resolution and analyse an image at 2 seconds. I create a python file for taking photos and analyse them, works pretty well but after analysing face D stops and doesnt give me that numbers...
The lines that i wrote for this is : 

       cmd = "rubiks-cube-tracker.py --directory /home/pi/cubescan"
       log.info(cmd)
       output = check_output(cmd, shell=True)

where cubescan is the folder where i store the photos.
