### ISSUE TITLE
Identify the problem

### ISSUE THREAD

**Issue by fovVdk** [dwalton76/rubiks-cube-tracker#3]
my  Rubik's cube is 3x3x3 ,but it find only 2x2x2 
![32dbed7f-63ce-4fe0-ba50-332c965014d2](https://user-images.githubusercontent.com/21216647/48990450-6f8a6100-f169-11e8-9e6c-1289e4c53129.png)

**Comment by dwalton76** [comment]
Sorry for taking 6 months to reply :( Can you try the latest copy of the code and see if this is still an issue? I fixed a lot of bugs a couple of months ago
